# Generated by Django 5.1.4 on 2025-03-24 16:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('file_status', models.CharField(choices=[('true', 'Option1'), ('false', 'Option2')], default='false', max_length=10)),
                ('video_status', models.CharField(choices=[('true', 'Option1'), ('false', 'Option2')], default='false', max_length=10)),
                ('file_path', models.CharField(default='null', max_length=500)),
                ('video_path', models.CharField(default='null', max_length=100)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('dob', models.DateField(null=True)),
                ('profile_image', models.CharField(blank=True, max_length=100, null=True)),
                ('google_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
